### ISSUE TITLE
What is Burst of data for my Ansluta remote control

### ISSUE THREAD

**Issue by saytinh** [NDBCK/Ansluta-Remote-Controller#1]
First I would like to thank you so much for what you have done. It's a great while I have took so much time to replicate the Ansluta remote control but can not gone to the end.

For my remote control, I've tried with RF Link firmware (http://www.nemcon.nl/blog2/download). It works but not stable at all. Using their firmware, I can decode the signal from the remote control and send command to turn 50%, 100%, 50%, OFF. However RFLink is not an open source so I can't find out why the control is not very stable. 

Below is log file when I used with RFLink. Could you take a look at it and give me my Bust of data or what esle so that I can try my Ansluta remote control with your code. Thank you in advance.

<img src="https://dl2.pushbulletusercontent.com/OtNrQ8dkHQl5CMYwszuNPjcLOCTWAARD/Screenshot%202016-11-01%2000.14.20.png">

**Comment by NDBCK** [comment]
I know the RFlink firmware, I asked them if they could share the source code of the project for the IKEA lamps but I never got it (so I went reverse engineering). I never tested their software...

Looking at your print screen it looks like your address bytes are: 0x3C and 0x22

So if you change in the arduino code the two address bytes by your bytes it should work.

Like so:
#include "cc2500_REG.h"
#include "cc2500_VAL.h"
#include <SPI.h>

#define CC2500_SIDLE    0x36      // Exit RX / TX, turn
#define CC2500_STX      0x35      // Enable TX. If in RX state, only enable TX if CCA passes
#define CC2500_SFTX     0x3B      // Flush the TX FIFO buffer. Only issue SFTX in IDLE or TXFIFO_UNDERFLOW states
#define CC2500_SRES     0x30


char vertragingA = 1;    // No delay is also possible
char vertragingB = 200;  // 100 doesn't work (to fast), 150 works + safety margin (empirical)
int KNOP1;

void WriteReg(char addr, char value){
  digitalWrite(SS,LOW);
  while (digitalRead(MISO) == HIGH) {
    };
  SPI.transfer(addr);
  delayMicroseconds(vertragingB);
  SPI.transfer(value);
  digitalWrite(SS,HIGH);
}

void SendStrobe(char strobe){
  digitalWrite(SS,LOW);
  
  while (digitalRead(MISO) == HIGH) {
  };
  SPI.transfer(strobe);
  digitalWrite(SS,HIGH);
  delayMicroseconds(vertragingB);
}

void init_CC2500(){
  WriteReg(REG_IOCFG2,VAL_IOCFG2);
  WriteReg(REG_IOCFG0,VAL_IOCFG0);
  WriteReg(REG_PKTLEN,VAL_PKTLEN);
  WriteReg(REG_PKTCTRL1,VAL_PKTCTRL1);
  WriteReg(REG_PKTCTRL0,VAL_PKTCTRL0);
  WriteReg(REG_ADDR,VAL_ADDR);
  WriteReg(REG_CHANNR,VAL_CHANNR);
  WriteReg(REG_FSCTRL1,VAL_FSCTRL1);
  WriteReg(REG_FSCTRL0,VAL_FSCTRL0);
  WriteReg(REG_FREQ2,VAL_FREQ2);
  WriteReg(REG_FREQ1,VAL_FREQ1);
  WriteReg(REG_FREQ0,VAL_FREQ0);
  WriteReg(REG_MDMCFG4,VAL_MDMCFG4);
  WriteReg(REG_MDMCFG3,VAL_MDMCFG3);
  WriteReg(REG_MDMCFG2,VAL_MDMCFG2);
  WriteReg(REG_MDMCFG1,VAL_MDMCFG1);
  WriteReg(REG_MDMCFG0,VAL_MDMCFG0);
  WriteReg(REG_DEVIATN,VAL_DEVIATN);
  WriteReg(REG_MCSM2,VAL_MCSM2);
  WriteReg(REG_MCSM1,VAL_MCSM1);
  WriteReg(REG_MCSM0,VAL_MCSM0);
  WriteReg(REG_FOCCFG,VAL_FOCCFG);
  WriteReg(REG_BSCFG,VAL_BSCFG);
  WriteReg(REG_AGCCTRL2,VAL_AGCCTRL2);
  WriteReg(REG_AGCCTRL1,VAL_AGCCTRL1);
  WriteReg(REG_AGCCTRL0,VAL_AGCCTRL0);
  WriteReg(REG_WOREVT1,VAL_WOREVT1);
  WriteReg(REG_WOREVT0,VAL_WOREVT0);
  WriteReg(REG_WORCTRL,VAL_WORCTRL);
  WriteReg(REG_FREND1,VAL_FREND1);
  WriteReg(REG_FREND0,VAL_FREND0);
  WriteReg(REG_FSCAL3,VAL_FSCAL3);
  WriteReg(REG_FSCAL2,VAL_FSCAL2);
  WriteReg(REG_FSCAL1,VAL_FSCAL1);
  WriteReg(REG_FSCAL0,VAL_FSCAL0);
  WriteReg(REG_RCCTRL1,VAL_RCCTRL1);
  WriteReg(REG_RCCTRL0,VAL_RCCTRL0);
  WriteReg(REG_FSTEST,VAL_FSTEST);
  WriteReg(REG_TEST2,VAL_TEST2);
  WriteReg(REG_TEST1,VAL_TEST1);
  WriteReg(REG_TEST0,VAL_TEST0);
  WriteReg(REG_DAFUQ,VAL_DAFUQ);
}

boolean LIGHTOFF = false;     //Used for turning the light on and off

void setup(){
  pinMode(2, INPUT_PULLUP);
  pinMode(SS,OUTPUT);

  SPI.begin();
  SPI.beginTransaction(SPISettings(6000000, MSBFIRST, SPI_MODE0));    //Faster SPI mode, maximal speed for the CC2500 without the need for extra delays
  digitalWrite(SS,HIGH);
  SendStrobe(CC2500_SRES); //0x30 SRES Reset chip.
  init_CC2500();
//  SendStrobe(CC2500_SPWD); //Enter power down mode    -   Not used in the prototype
  WriteReg(0x3E,0xFF);  //Maximum transmit power - write 0xFF to 0x3E (PATABLE)
}

void loop(){

if(LIGHTOFF){
    for(byte i=0;i<50;i++){       //Send 50 times
      SendStrobe(CC2500_SIDLE);   //0x36 SIDLE Exit RX / TX, turn off frequency synthesizer and exit Wake-On-Radio mode if applicable.
      SendStrobe(CC2500_SFTX);    //0x3B SFTX Flush the TX FIFO buffer. Only issue SFTX in IDLE or TXFIFO_UNDERFLOW states.
      digitalWrite(SS,LOW);
      while (digitalRead(MISO) == HIGH) { };
      SPI.transfer(0x7F);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x06);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x55);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x01);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x3C);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x22);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x03);                     //3 = Turn light on full power
      delayMicroseconds(vertragingA);
      SPI.transfer(0xAA);
      delayMicroseconds(vertragingA);
      SPI.transfer(0xFF);
      digitalWrite(SS,HIGH);
      SendStrobe(CC2500_STX);                 //0x35 STX In IDLE state: Enable TX. Perform calibration first if MCSM0.FS_AUTOCAL=1. If in RX state and CCA is enabled: Only go to TX if channel is clear
      delayMicroseconds(vertragingA*10);      //Longer delay for transmitting
    }
    LIGHTOFF=false;
  }
  else{
     for(byte i=0;i<50;i++){  //Send 50 times
      SendStrobe(CC2500_SIDLE); //0x36 SIDLE Exit RX / TX, turn off frequency synthesizer and exit Wake-On-Radio mode if applicable.
      SendStrobe(CC2500_SFTX);  //0x3B SFTX Flush the TX FIFO buffer. Only issue SFTX in IDLE or TXFIFO_UNDERFLOW states.
      digitalWrite(SS,LOW);
      while (digitalRead(MISO) == HIGH) { };
      SPI.transfer(0x7F);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x06);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x55);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x01);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x3C);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x22);
      delayMicroseconds(vertragingA);
      SPI.transfer(0x01);               //1 = Turn light off
      delayMicroseconds(vertragingA);
      SPI.transfer(0xAA);
      delayMicroseconds(vertragingA);
      SPI.transfer(0xFF);
      digitalWrite(SS,HIGH);
      SendStrobe(CC2500_STX); //0x35 STX In IDLE state: Enable TX. Perform calibration first if MCSM0.FS_AUTOCAL=1. If in RX state and CCA is enabled: Only go to TX if channel is clear
      delayMicroseconds(vertragingA*10);
    }
    LIGHTOFF=true;
  }
 
}

**Comment by NDBCK** [comment]
I've also noticed some things that have an influence on the stability.

*The timing (delays) of the SPI signals is important to slow or to fast gives problems. When I have some better values, I will share them.
*The original remote sends the sequence 50 times in the hope that it's received at least once, you could raise this value.
*The transmitted power is changeable, in the arduino code I changed it to the maximum.
*There are CC2500 module with a power amplifier on ebay (search for CC2500 LNA PA - I didn't test those)
*My original IKEA remote has also sometimes missed presses even when it's only 5m away.

**Comment by saytinh** [comment]
Thank you. I'll try and get back to you soon.

**Comment by NDBCK** [comment]
I've rewritten the demo code (https://github.com/NDBCK/Ansluta-Remote-Controller/blob/master/AnslutaDemoCode/AnslutaDemoCode.ino)

There where some errors in my original code (especially with the delays).
I also made it so you can read your address by listening to the data from another remote.

**Comment by saytinh** [comment]
Well done. I've tried and it's running smooth. The AnslutaDemoCode.ino sometimes can't recognize the address of remote control. But when it has got the address, the sketch running stable. Thanks

**Comment by NDBCK** [comment]
Hmm could it be that it sometimes misses the address because it only scans for the adress once every 5 seconds?

**Comment by saytinh** [comment]
No problem. It's still so good. Thanks
